version: "3"

services:
  springmysql:
    restart: always
    image: mysql:5.6
    container_name: springboot-mysql
    volumes:
      - /var/lib/postgresql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Admin#123
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=naresh240
      - MYSQL_PASSWORD=N@resh@240
  spring-boot:
    restart: always
    image: naresh240/springboot-employeejdbc:latest
    container_name: springboot-employeejdbc
    ports:
      - 8080:8080
    links:
      - springmysql
